# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2022 Datadog, Inc.
apiVersion: v2
name: chaos-controller
description: Datadog Chaos Controller chart
version: 2.0.0
